when:
  instance: ci.schnabel.org
  repo: kokuwaio/renovate-config-validator
  event: push
  branch: main
  path: README.md

steps:

  metadata:
    image: kokuwaio/dockerhub-metadata
    settings:
      repository: kokuwaio/renovate-config-validator
      description-short: A Woodpecker CI plugin for renovate-config-validator to lint shell files.
      categories: [developer-tools, integration-and-delivery]
      username: {from_secret: DOCKERHUB_USERNAME}
      password: {from_secret: DOCKERHUB_PASSWORD}
